version: "3.8"
services:
  api:
    build:
      dockerfile: Dockerfile
    command: sleep infinity
    environment:
      PGHOST: postgres
      PGPORT: ${PGPORT}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      NODE_ENV: development
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    volumes:
      - .:/usr/app
    depends_on:
      postgres:
        condition: service_healthy
  pgAdmin:
    image: dpage/pgadmin4:6.14
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_LOGIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_LOGIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
  postgres:
    image: postgres:14.5-alpine3.16
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "${PGPORT}"
    healthcheck:
      test: pg_isready -U ${PGUSER} -p ${PGPORT} -d ${PGDATABASE}
      interval: 15s
      timeout: 1s
      start_period: 3s
    restart: on-failure
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
