apiVersion: skaffold/v3
kind: Config
metadata:
  name: consents-api-node
build:
  artifacts:
    - image: docker.io/kazirashid/consents-api-node
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  local:
    push: true
manifests:
  helm:
    releases:
      - name: consents-api-node
        chartPath: helm
        setValueTemplates:
          image.registry: '{{.IMAGE_DOMAIN}}'
          image.repository: '{{.IMAGE_REPO_NO_DOMAIN}}'
          image.tag: '{{.IMAGE_TAG}}@{{.IMAGE_DIGEST}}'
deploy:
  helm: {}
