---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      name: api
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/kazimanzurrashid/consents-node
          env:
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_DB
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
            - name: PGHOST
              value: postgres
            - name: PGPORT
              value: "5432"
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3001"
          readinessProbe:
            httpGet:
              port: 3001
              path: /
            periodSeconds: 15
            initialDelaySeconds: 10
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 50m
              memory: 300Mi
            limits:
              cpu: 300m
              memory: 500Mi
          ports:
            - containerPort: 3001
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicas: 3
  maxReplicas: 12
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - targetPort: 3001
      port: 3001
      protocol: TCP
      nodePort: 30100
