version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 18-bullseye
    command: sleep infinity
    environment:
      PGHOST: postgres
      PGPORT: ${PGPORT}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      NODE_ENV: development
      PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ..:/workspace:cached
  pgAdmin:
    image: dpage/pgadmin4:6.14
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_LOGIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_LOGIN_PASSWORD}
    ports:
      - '${PGADMIN_PORT}:80'
  postgres:
    image: postgres:14.5-alpine3.16
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - '${PGPORT}:${PGPORT}'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  pg-admin-data:
  postgres-data:
