name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install
        run: |
          npm ci --ignore-scripts
      - name: Lint
        run: |
          npm run format && npm run lint && npm run compile
      - name: Test
        run: |
          npm run coverage
      - name: Upload coverage
        uses: codecov/codecov-action@v3
      - name: Publish Docker Image
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: VaultVulp/gp-docker-action@1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: consents-node
