name: CI
on: [push, pull_request]
env:
  publishDockerImage: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install
        run: |
          npm ci --ignore-scripts
      - name: Lint
        run: |
          npm run format && npm run lint && npm run compile
      - name: Test
        run: |
          npm run coverage
      - name: Upload coverage
        uses: codecov/codecov-action@v3
      - name: Set up Docker Buildx
        if: ${{ env.publishDockerImage }}
        uses: docker/setup-buildx-action@v2
      - name: DockerHub Login
        if: ${{ env.publishDockerImage }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Image
        if: ${{ env.publishDockerImage }}
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/consents-node
